name: Deploy Lambda Function
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_lambda:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
        # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: zip Lambda Function
        run: |
          zip -r9 lambda.zip lambda_function.py
      - name: AWS Deploy
        run: |
          aws lambda update-function-code --function-name get_target_data --zip-file fileb://lambda.zip
